import OpenAI from 'openai';
import { LLM_PROVIDERS, LLMMessage, LLMResponse, LLMConfig } from '../types/llm';
import { LLMConfigModel } from '../models/LLMConfig';

const PLACEHOLDER_PATTERNS = [
  'your_',
  '_here',
  'xxx',
  'placeholder',
  'changeme',
  'change_me',
  'example',
  'sk-placeholder',
];

function isPlaceholderApiKey(apiKey: string): boolean {
  if (!apiKey || apiKey.trim().length < 10) return true;
  const lower = apiKey.toLowerCase();
  return PLACEHOLDER_PATTERNS.some((p) => lower.includes(p));
}

function generateDemoResponse(messages: LLMMessage[], config: LLMConfig): LLMResponse {
  const lastUserMessage = messages.filter((m) => m.role === 'user').pop();
  const userContent = lastUserMessage?.content || '';

  let responseContent = '';

  if (userContent.includes('summarize') || userContent.includes('summary') || config.model === 'demo-summary') {
    responseContent = '[Demo Mode] This is a simulated summary of your note. The note covers several key topics including the main subject, supporting details, and conclusions. In production mode with a real AI provider, this would be an intelligent summary generated by the AI model based on your actual note content.';
  } else if (userContent.includes('keyword') || userContent.includes('keywords') || config.model === 'demo-keywords') {
    responseContent = 'note, AI, knowledge-base, summary, demo, markdown, search';
  } else if (userContent.includes('optimize') || userContent.includes('rewrite')) {
    responseContent = '[Demo Mode] This is a simulated rewrite of your note. The content has been reorganized for better clarity and readability. In production mode, the AI would intelligently optimize your note based on the instruction provided.';
  } else if (userContent.includes('OK') || userContent.includes('Hello')) {
    responseContent = 'OK - Demo mode connection test successful!';
  } else {
    responseContent = '[Demo Mode] Hello! I am a demo AI assistant. This is a simulated response to demonstrate the application functionality. In production mode with a real AI provider (OpenAI, Kimi, DeepSeek, etc.), you would get intelligent AI-generated responses based on your notes and questions.\n\nTo enable real AI features, please configure an API key in Settings > API Key Management.\n\nYour message was: ' + (userContent.substring(0, 100) + (userContent.length > 100 ? '...' : ''));
  }

  return {
    content: responseContent,
    model: config.model || 'demo-chat',
    provider: 'demo',
    usage: {
      prompt_tokens: userContent.length,
      completion_tokens: responseContent.length,
      total_tokens: userContent.length + responseContent.length,
    },
  };
}

class LLMService {
  private providers: Map<string, OpenAI | null> = new Map();
  private userProviders: Map<string, OpenAI> = new Map();

  constructor() {
    this.initProviders();
  }

  private async initProviders() {
    this.providers.set('demo', null);
    console.log('LLM Provider loaded: Demo (Free)');
    // Do not load shared providers. Users may only use demo or their own saved keys.
    console.log('✅ All available providers:', Array.from(this.providers.keys()));
  }

  private async loadFromEnv() {
    Object.entries(LLM_PROVIDERS).forEach(([key, provider]) => {
      if (provider.isDemo) return;
      const apiKey = process.env[provider.apiKeyEnv];
      if (apiKey && !isPlaceholderApiKey(apiKey)) {
        const client = new OpenAI({
          apiKey,
          baseURL: provider.baseURL,
        });
        this.providers.set(key, client);
        console.log('LLM Provider loaded from env: ' + provider.name);
      }
    });
  }

  private async loadFromDatabase() {
    try {
      const configs = await LLMConfigModel.findAll();
      console.log('Loading', configs.length, 'providers from database...');
      for (const config of configs) {
        if (config.is_active && config.api_key && !isPlaceholderApiKey(config.api_key)) {
          const provider = LLM_PROVIDERS[config.provider_key];
          if (provider && !provider.isDemo && !this.providers.has(config.provider_key)) {
            const client = new OpenAI({
              apiKey: config.api_key,
              baseURL: provider.baseURL,
            });
            this.providers.set(config.provider_key, client);
            console.log('✅ LLM Provider loaded from DB:', provider.name, '(', config.provider_key, ')');
          }
        }
      }
    } catch (error) {
      console.error('Error loading from DB:', error);
    }
  }

  async reloadProvider(providerKey: string, apiKey: string): Promise<void> {
    const provider = LLM_PROVIDERS[providerKey];
    if (!provider) {
      throw new Error('Unknown provider: ' + providerKey);
    }
    if (provider.isDemo) return;
    const client = new OpenAI({
      apiKey,
      baseURL: provider.baseURL,
    });
    this.providers.set(providerKey, client);
    console.log('LLM Provider reloaded: ' + provider.name);
  }

  removeProvider(providerKey: string): void {
    if (providerKey === 'demo') return;
    this.providers.delete(providerKey);
    const provider = LLM_PROVIDERS[providerKey];
    if (provider) {
      console.log('LLM Provider removed: ' + provider.name);
    }
  }

  removeUserProvider(userId: number, providerKey: string): void {
    this.userProviders.delete(`${userId}:${providerKey}`);
  }

  getAvailableProviders(): string[] {
    return Array.from(this.providers.keys());
  }

  getProviderInfo(providerKey: string) {
    return LLM_PROVIDERS[providerKey];
  }

  getAvailableModels(providerKey: string): string[] {
    const provider = LLM_PROVIDERS[providerKey];
    if (!provider || !this.providers.has(providerKey)) {
      return [];
    }
    return provider.models;
  }

  getAllAvailableModels(): Array<{ provider: string; model: string; providerName: string }> {
    const models: Array<{ provider: string; model: string; providerName: string }> = [];
    this.providers.forEach((_, key) => {
      const provider = LLM_PROVIDERS[key];
      provider.models.forEach((model) => {
        models.push({
          provider: key,
          model,
          providerName: provider.name,
        });
      });
    });
    return models;
  }

  private getClient(provider: string): OpenAI {
    const client = this.providers.get(provider);
    if (!client) {
      throw new Error('LLM provider not configured: ' + provider);
    }
    return client;
  }

  private async getClientForUser(providerKey: string, userId?: number): Promise<OpenAI> {
    if (userId) {
      const cacheKey = `${userId}:${providerKey}`;
      const cached = this.userProviders.get(cacheKey);
      if (cached) {
        return cached;
      }

      const config = await LLMConfigModel.findByProvider(userId, providerKey);
      const provider = LLM_PROVIDERS[providerKey];
      if (
        config?.is_active &&
        config.api_key &&
        provider &&
        !provider.isDemo &&
        !isPlaceholderApiKey(config.api_key)
      ) {
        const client = new OpenAI({
          apiKey: config.api_key,
          baseURL: provider.baseURL,
        });
        this.userProviders.set(cacheKey, client);
        return client;
      }
    }

    throw new Error('LLM provider not configured for current user: ' + providerKey);
  }

  async chatCompletion(
    messages: LLMMessage[],
    config: LLMConfig,
    userId?: number
  ): Promise<LLMResponse> {
    if (config.provider === 'demo' || LLM_PROVIDERS[config.provider]?.isDemo) {
      await new Promise((resolve) => setTimeout(resolve, 500 + Math.random() * 1000));
      return generateDemoResponse(messages, config);
    }

    const client = await this.getClientForUser(config.provider, userId);
    console.log('Calling LLM:', {
      provider: config.provider,
      model: config.model,
      baseURL: LLM_PROVIDERS[config.provider]?.baseURL,
      messageCount: messages.length
    });

    try {
      const response = await client.chat.completions.create({
        model: config.model,
        messages: messages.map((m) => ({
          role: m.role as 'user' | 'assistant' | 'system',
          content: m.content,
        })),
        temperature: config.temperature ?? 0.7,
        max_tokens: config.maxTokens ?? 2000,
      });

      console.log('LLM call successful:', {
        model: response.model,
        usage: response.usage
      });

      return {
        content: response.choices[0].message.content || '',
        model: response.model,
        provider: config.provider,
        usage: response.usage
          ? {
              prompt_tokens: response.usage.prompt_tokens,
              completion_tokens: response.usage.completion_tokens,
              total_tokens: response.usage.total_tokens,
            }
          : undefined,
      };
    } catch (error: any) {
      console.error('LLM call failed:', {
        provider: config.provider,
        model: config.model,
        error: error.message,
        response: error.response?.data || error.cause
      });
      throw error;
    }
  }

  async createEmbedding(
    text: string,
    provider: string,
    model: string,
    userId?: number
  ): Promise<number[]> {
    if (provider === 'demo') {
      return Array.from({ length: 1536 }, () => Math.random() * 2 - 1);
    }
    const client = await this.getClientForUser(provider, userId);
    const response = await client.embeddings.create({ model, input: text });
    return response.data[0].embedding;
  }

  async generateSummary(content: string, config: LLMConfig, userId?: number): Promise<string> {
    const messages: LLMMessage[] = [
      { role: 'system', content: 'You are a professional note assistant. Please summarize the following note content concisely, highlighting key points. Answer in the same language as the content.' },
      { role: 'user', content: 'Please summarize the following note:\n\n' + content },
    ];
    const response = await this.chatCompletion(messages, config, userId);
    return response.content;
  }

  async extractKeywords(content: string, config: LLMConfig, userId?: number): Promise<string[]> {
    const messages: LLMMessage[] = [
      { role: 'system', content: 'You are a professional note assistant. Please extract 5-10 keywords from the following note, separated by commas. Answer in the same language as the content.' },
      { role: 'user', content: 'Please extract keywords from the following note:\n\n' + content },
    ];
    const response = await this.chatCompletion(messages, config, userId);
    return response.content.split(',').map((k) => k.trim()).filter((k) => k.length > 0);
  }

  async rewriteNote(content: string, instruction: string | undefined, config: LLMConfig, userId?: number): Promise<string> {
    const systemPrompt = instruction
      ? 'You are a professional writing assistant. Please optimize the following note according to the user request: ' + instruction
      : 'You are a professional writing assistant. Please optimize the following note to make it clearer, more organized, and easier to read.';
    const messages: LLMMessage[] = [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: 'Please optimize the following note:\n\n' + content },
    ];
    const response = await this.chatCompletion(messages, config, userId);
    return response.content;
  }

  async ragAnswer(question: string, context: string[], config: LLMConfig, userId?: number): Promise<string> {
    const contextText = context.join('\n\n---\n\n');
    if (contextText.trim().length === 0) {
      return /[\u4e00-\u9fff]/.test(question)
        ? '我在知识库里没有找到可靠依据来回答这个问题。'
        : 'I could not find reliable information in the knowledge base to answer this question.';
    }

    const messages: LLMMessage[] = [
      { role: 'system', content: 'You are a trustworthy knowledge-base Q&A assistant. Answer only from the Reference context below. Cite every factual claim with source numbers like [1] or [2], matching the [Source N: "title"] labels. If the Reference context does not contain enough information, say that the knowledge base has no reliable basis for the answer. If the context is empty or only demo fallback content, do not invent an answer or citations. Answer in the same language as the question.\n\nReference context:\n' + contextText },
      { role: 'user', content: question },
    ];
    const response = await this.chatCompletion(messages, config, userId);
    return response.content;
  }
}

export const llmService = new LLMService();
